--                                                                                                                                                                     
- hostname: 'index.docker.io'                                                                                                                                           
- hostname: 'registry.hub.docker.com'                                                                                                                                   
- hostname: 'auth.docker.io'                                                                                                                                            
- hostname: 'hub.docker.com'                                                                                                                                            
- hostname: 'registry-1.docker.io' 
  port_set:
    - port_number: 80
      type: "HTTP"
    - port_number: 443
      type: "HTTPS"