#!/bin/bash
echo "=> Building the binary"
docker run --privileged \
  -v $(pwd):/src \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e DOCKER_BUILD_CONTEXT=hooks \
  -e OUTPUT=abghand \
  centurylink/golang-builder
